apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete
  labels:
    app: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: lanchonete-container
          image: diegobbrito17/lanchonete:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_port
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_server
          livenessProbe:
            httpGet:
              path: /lanchonete/actuator/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /lanchonete/actuator/health
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1