apiVersion: v1
kind: Service
metadata:
  name: lanchonetedb
  labels:
    app: lanchonetedb
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: lanchonetedb
    tier: database
  clusterIP: None