apiVersion: v1
kind: Service
metadata:
  name: svc-lanchonete
  labels:
    app: lanchonete
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: lanchonete
  type: NodePort