name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and push it to ECR 
          docker build -t 103199998923.dkr.ecr.us-east-1.amazonaws.com/lanchonete:latest .
          echo "Pushing image to ECR..."
          docker push 103199998923.dkr.ecr.us-east-1.amazonaws.com/lanchonete:latest
