name: Java CI Build and Push Docker Image to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get version from pom.xml
        id: get_version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Push to ECR
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            public.ecr.aws/${{ secrets.AWS_KEY_ECR }}/lanchonete:latest
            public.ecr.aws/${{ secrets.AWS_KEY_ECR }}/lanchonete:${{ steps.get_version.outputs.version }}
